CODE/app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

CODE/app/__init__.py
from flask import Flask
from flask_socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.host = "0.0.0.0"
    app.port = 5050
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

CODE/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

CODE/app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm
import pickledb

db = pickledb.load("db.dat",False)



@main.route('/', methods=['GET', 'POST'])
def index():
    print(request.form)
    """Login form to enter a room."""
    form = LoginForm()
    if request.method == "POST":
        _f = db.get(request.form.get("room"))
        if _f:
            if _f == request.form["password"]:
                session['name'] = request.form["name"]
                session['room'] = request.form["room"]
                return redirect(url_for(".chat"))
            else:
                return render_template('index.html', form=form)
        else:
            db.set(request.form.get("room"),request.form["password"])
            session['name'] = request.form["name"]
            session['room'] = request.form["room"]
            return redirect(url_for(".chat"))

    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

CODE/app/templates/chat.html
<html>
    <head>

    <style>
* {
  box-sizing: border-box;
}

body {
  background-color: #669999;
  font-family: "Calibri", "Roboto", sans-serif;
}

.chat_window {
  position: absolute;
  width: calc(100% - 20px);
  max-width: 800px;
  height: 500px;
  border-radius: 10px;
  background-color: #fff;
  left: 50%;
  top: 50%;
  transform: translateX(-50%) translateY(-50%);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);
  background-color: #f8f8f8;
  overflow: hidden;
}

.top_menu {
  background-color: #fff;
  width: 100%;
  padding: 20px 0 15px;
  box-shadow: 0 1px 30px rgba(0, 0, 0, 0.1);
}
.top_menu .buttons {
  margin: 3px 0 0 20px;
  position: absolute;
}
.top_menu .buttons .button {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  display: inline-block;
  margin-right: 10px;
  position: relative;
}
.top_menu .buttons .button.close {
  background-color: #f5886e;
}
.top_menu .buttons .button.minimize {
  background-color: #fdbf68;
}
.top_menu .buttons .button.maximize {
  background-color: #a3d063;
}
.top_menu .title {
  text-align: center;
  color: #bcbdc0;
  font-size: 20px;
}

.messages {
  position: relative;
  list-style: none;
  padding: 20px 10px 0 10px;
  margin: 0;
  height: 347px;
  overflow: scroll;
}
.messages .message {
  clear: both;
  overflow: hidden;
  margin-bottom: 20px;
  transition: all 0.5s linear;
  opacity: 0;
}
.messages .message.left .avatar {
  background-color: #f5886e;
  float: left;
}
.messages .message.left .text_wrapper {
  background-color: #ffe6cb;
  margin-left: 20px;
}
.messages .message.left .text_wrapper::after, .messages .message.left .text_wrapper::before {
  right: 100%;
  border-right-color: #ffe6cb;
}
.messages .message.left .text {
  color: #c48843;
}
.messages .message.right .avatar {
  background-color: #fdbf68;
  float: right;
}
.messages .message.right .text_wrapper {
  background-color: #c7eafc;
  margin-right: 20px;
  float: right;
}
.messages .message.right .text_wrapper::after, .messages .message.right .text_wrapper::before {
  left: 100%;
  border-left-color: #c7eafc;
}
.messages .message.right .text {
  color: #45829b;
}
.messages .message.appeared {
  opacity: 1;
}
.messages .message .avatar {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  display: inline-block;
}
.messages .message .text_wrapper {
  display: inline-block;
  padding: 20px;
  border-radius: 6px;
  width: calc(100% - 85px);
  min-width: 100px;
  position: relative;
}
.messages .message .text_wrapper::after, .messages .message .text_wrapper:before {
  top: 18px;
  border: solid transparent;
  content: " ";
  height: 0;
  width: 0;
  position: absolute;
  pointer-events: none;
}
.messages .message .text_wrapper::after {
  border-width: 13px;
  margin-top: 0px;
}
.messages .message .text_wrapper::before {
  border-width: 15px;
  margin-top: -2px;
}
.messages .message .text_wrapper .text {
  font-size: 18px;
  font-weight: 300;
}

.bottom_wrapper {
  position: relative;
  width: 100%;
  background-color: #fff;
  padding: 20px 20px;
  position: absolute;
  bottom: 0;
}
.bottom_wrapper .message_input_wrapper {
  display: inline-block;
  height: 50px;
  border-radius: 25px;
  border: 1px solid #bcbdc0;
  width: calc(100% - 160px);
  position: relative;
  padding: 0 20px;
}
.bottom_wrapper .message_input_wrapper .message_input {
  border: none;
  height: 100%;
  box-sizing: border-box;
  width: calc(100% - 40px);
  position: absolute;
  outline-width: 0;
  color: gray;
}
.bottom_wrapper .send_message {
  width: 140px;
  height: 50px;
  display: inline-block;
  border-radius: 50px;
  background-color: #669999;
  border: 2px solid #669999;
  color: #fff;
  cursor: pointer;
  transition: all 0.2s linear;
  text-align: center;
  float: right;
}
.bottom_wrapper .send_message:hover {
  color: #a3d063;
  background-color: #fff;
}
.bottom_wrapper .send_message .text {
  font-size: 18px;
  font-weight: 300;
  display: inline-block;
  line-height: 48px;
}

.message_template {
  display: none;
}

    </style>




        <title>Flask-SocketIO-Chat: {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.index') }}";
                });
            }
        </script>
    </head>
    <body>
     



<div class="chat_window">
<div class="top_menu">
<div class="buttons">
<div class="button close">
</div><div class="button minimize"></div>
<div class="button maximize"></div>
</div><div class="title">Chat</div></div>
<ul class="messages">
<textarea id="chat" cols="80" rows="20"></textarea><br><br>
</ul><div class="bottom_wrapper clearfix">
<div class="message_input_wrapper">
<input class="message_input" placeholder="Type your message here..." / id="text">
</div>
    <input type="file">
<input type="button" onclick="leave_room();" class="send_message icon" value="Leave Room"></div></div></div></div>
<div class="message_template"><li class="message"><div class="avatar"></div>
<div class="text_wrapper"><div class="text"></div></div></li></div>
    </body>
</html>

CODE/app/templates/index.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>

<style>

/*--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
--*/
/* reset */
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,dl,dt,dd,ol,nav ul,nav li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;}
article, aside, details, figcaption, figure,footer, header, hgroup, menu, nav, section {display: block;}
ol,ul{list-style:none;margin:0px;padding:0px;}
blockquote,q{quotes:none;}
blockquote:before,blockquote:after,q:before,q:after{content:'';content:none;}
table{border-collapse:collapse;border-spacing:0;}
/* start editing from here */
a{text-decoration:none;}
.txt-rt{text-align:right;}/* text align right */
.txt-lt{text-align:left;}/* text align left */
.txt-center{text-align:center;}/* text align center */
.float-rt{float:right;}/* float right */
.float-lt{float:left;}/* float left */
.clear{clear:both;}/* clear float */
.pos-relative{position:relative;}/* Position Relative */
.pos-absolute{position:absolute;}/* Position Absolute */
.vertical-base{	vertical-align:baseline;}/* vertical align baseline */
.vertical-top{	vertical-align:top;}/* vertical align top */
nav.vertical ul li{	display:block;}/* vertical menu */
nav.horizontal ul li{	display: inline-block;}/* horizontal menu */
img{max-width:100%;}
/*end reset*/
body{
	font-family: 'Kotta One', serif;
	background: #669999;
}
.header {
    text-align: center;
    margin-top: 4em;
}
.header h1 {
    font-size: 3em;
    color: #fff;
    font-weight: 400;
}
.main-section {
    width: 37%;
    margin: 3em auto 0;
	text-align: center;
}
.registration-section h2 {
    font-size: 2em;
    text-transform: capitalize;
	    color: #669999;
}
.registration-section {
    background: #fff;    
	border: 1px solid #999;
	padding: 2em 0em;   
	box-shadow: 0px 7px 9px 4px rgba(16, 16, 16, 0.48);
}
.social-icons {
    border-top: 1px solid#ddd;
    border-bottom: 1px solid#ddd;
    padding: 1em 0;
	margin-top:1em;
}
.social-icons span {
    font-size: .85em;
    color: #555;
	margin: 0 .5em;
}
.social-icons i  {
    width: 38px;
    height: 38px;
    background: url(../images/img-sprite.png) no-repeat 0px 0px;
    display: inline-block;
    vertical-align: middle;
    margin: 0 5px 0 0px;
    background-size: 150px;
}
.social-icons i.icon1{
	background-position:-38px 0px
}
.social-icons i.icon2{
	background-position:-76px 0px
}
.login-form {
    float: left;
    width: 100%;
}
.registration-form {
    float: left;
	width: 49%;
    border-left: 1px solid #999;
}
.login-form input[type="text"] {
    padding: .5em 1em;
    width: 75%;
	margin-bottom: 1em;
	outline: none;
	font-size: 0.95em;
}
.login-form input[type="password"] {
    padding: .5em 1em;
    width: 75%;
	margin-bottom: 1em;
	outline: none;
	font-size: 0.95em;
}
.registration-form input[type="text"] {
    padding: .5em 1em;
    width: 75%;
	margin-bottom: 1em;
	outline: none;
	font-size: 0.95em;
}
.registration-form input[type="password"] {
    padding: .5em 1em;
    width: 75%;
	margin-bottom: 1em;
	outline: none;
	font-size: 0.95em;	 
}
.login-form span  {
    display: block;
	text-align: left;
    margin: 0 1em;
	color: #555;
}
.login-form input[type="submit"] {
    padding: .8em 2em;
    font-size: 1em;
    text-transform: capitalize;
    color: #fff;
	outline: none;
	border: 0;
	margin: 1em 1.2em 0 0;
    background: #669999;
    cursor: pointer;
    display: block;
    float: right;
	border-radius: 2px;
	font-family: 'Kotta One', serif;
	 transition:0.5s all;
	-webkit-transition:0.5s all;
	-moz-transition:0.5s all;
	-o-transition:0.5s all;
	-ms-transition:0.5s all;
}
.login-form input[type="submit"]:hover {
    background: #222;
}
.registration-form input[type="submit"]:hover {
    background: #222;
}
.registration-form input[type="submit"] {
    padding: .8em 2em;
    font-size: 1em;
    text-transform: capitalize;
    color: #fff;
	outline: none;
	border: 0;
	margin: 1em 1.2em 0 0;
    background: #669999;
    cursor: pointer;
    display: block;
    float: right;
	border-radius: 2px;
	font-family: 'Kotta One', serif;
	 transition:0.5s all;
	-webkit-transition:0.5s all;
	-moz-transition:0.5s all;
	-o-transition:0.5s all;
	-ms-transition:0.5s all;
}
.register-form {
    border-bottom: 1px solid #ddd;
    padding: 1.5em 0;
}
.registration-section p {
    font-size: 1em;
    margin-top: 1em;
    color: #555;
}
.registration-section p a {
    color: #669999;
    font-size: 1em;
}
.footer {
    text-align: center;
    padding: 3em 0;
}
::-web-input-placeholder{
	color:#494949;
	font-size:.95em;
}
.footer p {
    font-size: 1em;
    color: #fff;
    margin: 0px;
}
.footer p a {
    color: #fff;
}
.footer p a:hover {
    color: #000;
}
/**responsive*/
@media(max-width:1440px){
.main-section {
    width: 41%;
}
}
@media (max-width:1366px){
.main-section {
    width: 42%;
}
}
@media (max-width:1280px){
.main-section {
    width: 46%;
}
}
@media (max-width: 1080px){
.main-section {
    width: 57%;
}
.social-icons i {
   margin: 0 10px 0 0px;
}
.header h1 {
    font-size: 2.8em;
}
.registration-section h2 {
    font-size: 1.8em;
}
}
@media (max-width:991px){
.main-section {
    width: 60%;
}
}
@media (max-width: 800px){
.main-section {
    width: 73%;
}
}
@media (max-width:768px){
.main-section {
    width: 77%;
}
}
@media (max-width: 640px){
.main-section {
    width: 92%;
}
.header h1 {
    font-size: 2.5em;
}
.registration-form input[type="submit"],.login-form input[type="submit"] {
    padding: .5em 1em;
}
.registration-section {
    padding: 1.5em 0em;
}
}
@media(max-width:480px){
.header {
    margin-top: 3em;
}
.header h1 {
    font-size: 2.2em;
}
.registration-section h2 {
    font-size: 1.6em;
}
.registration-section p {
    font-size: .95em;
}
.social-icons span {
    display: block;
}
.social-icons i {
  margin: 13px 0px 0 0px;
 }
 .social-icons {
   padding: 0em 0 1em;
}
.login-form span {
   margin: 0 2em;
}
.login-form {
    float: none;
    width: 100%;
}
.registration-form {
    float: none;
    width: 100%;
}
.login-form input[type="submit"] {
	margin:0em 2em 1em 0;
}
.registration-form input[type="submit"] {
    margin: 1em 2em 0 0;
}
}
@media (max-width:320px){
.header {
    margin-top: 2em;
}
.main-section {
    width: 97%;
	margin: 2em auto 0;
}
.header h1 {
    font-size: 1.7em;
}
.registration-section h2 {
    font-size: 1.4em;
}
.login-form input[type="submit"] {
	margin:1em 2em 1em 0;
}
.login-form input[type="text"],.login-form input[type="password"],.registration-form input[type="text"],.registration-form input[type="password"] {
   width: 80%;
 }
.footer {
    padding: 2em 0;
}
}

</style>












<title>Dual Registration Form Responsive Widget Template | Home :: w3layouts</title>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Dual Registration Form  Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<!--web-fonts-->
<link href='//fonts.googleapis.com/css?family=Kotta+One' rel='stylesheet' type='text/css'><!--web-fonts-->
</head>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.js" ></script> 
<script type="text/javascript" src="app.js" ></script>

<body ng-app="app" ng-controller="controller">
<form method="POST">

		<!---header--->
		<div class="header">
		</div>
		<!---header--->
		<!---main--->
			<div class="main">
				<div class="main-section">
				<div class="registration-section">
					<h2>register or sign in</h2>
					<div class="social-icons">
						
						<a href="#"><i class="icon1"></i><span>Sign in with facebook</span></a> 
					
					<fb:login-button scope="public_profile,email" onlogin="checkLoginState();"></fb:login-button>
						
					</div>
					<div class="register-form">
					<div class="login-form">
					<form method="post" action="/">
						<input type="text" placeholder="Name" name="name">
						<input type="text" placeholder="Room" name="room">
                        <input type="password" placeholder="Room password" name="password">
						<span><input type="checkbox">Remember Me</span>
						<input type="submit" value="Enter Chatroom" ng-model="model_enter"></input>
					</form>
					</div>
					
					<div class="clear"></div>
					</div>
					<p>forgot your password? click<a href="#"> here </a></p>
				</div>
			</div>
			<div class="footer">
			<p>All rights reserved</p>
		</div>


   
</form>
		<!---main--->
		
		
		
		<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '670833423107086',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.8'
    });
    FB.AppEvents.logPageView();   
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>




 
		
		
</body>
</html>